project:
  type: website

website:
  title: "Chizoma Oparaji"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: EPPS6356
        menu: 
          - href: Assignment 1.qmd
            text: Assignment 1
          - href: Assignment 2.qmd
            text: Assignment 2
          
        
          
format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

