project:
  type: website

website:
  title: "Chizoma Oparaji"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "EPPS6356"
        menu: 
          - href: assignment1.qmd
            text: "Assignment 1"
          - href: Assignment2.qmd
            text: "Assignment 2"
          - href: Assignment3.qmd
            text: "Assignment 3"
          - href: Assignment4.qmd
            text: "Assignment 4"
          
        
          
format:
  html:
    theme: pulse
    css: styles.css
    fontsize: 1.5em
    mainfont: Open Sans 
    monofont: Inconsolata
    toc: true

editor: visual

