project:
  type: website

website:
  title: "Chizoma Oparaji"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - About
      - text: EPPS6356
        
          
format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

